

package io.github.lukmccall.pika.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.lukmccall.pika.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("pika-compiler/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("pika-compiler/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("fullTypeInfoAnnotations.kt")
  public void testFullTypeInfoAnnotations() {
    runTest("pika-compiler/testData/box/fullTypeInfoAnnotations.kt");
  }

  @Test
  @TestMetadata("fullTypeInfoBasic.kt")
  public void testFullTypeInfoBasic() {
    runTest("pika-compiler/testData/box/fullTypeInfoBasic.kt");
  }

  @Test
  @TestMetadata("fullTypeInfoFields.kt")
  public void testFullTypeInfoFields() {
    runTest("pika-compiler/testData/box/fullTypeInfoFields.kt");
  }

  @Test
  @TestMetadata("fullTypeInfoInheritance.kt")
  public void testFullTypeInfoInheritance() {
    runTest("pika-compiler/testData/box/fullTypeInfoInheritance.kt");
  }

  @Test
  @TestMetadata("typeInfoCustomClass.kt")
  public void testTypeInfoCustomClass() {
    runTest("pika-compiler/testData/box/typeInfoCustomClass.kt");
  }

  @Test
  @TestMetadata("typeInfoNestedGenerics.kt")
  public void testTypeInfoNestedGenerics() {
    runTest("pika-compiler/testData/box/typeInfoNestedGenerics.kt");
  }

  @Test
  @TestMetadata("typeInfoParameterized.kt")
  public void testTypeInfoParameterized() {
    runTest("pika-compiler/testData/box/typeInfoParameterized.kt");
  }

  @Test
  @TestMetadata("typeInfoSimpleTypes.kt")
  public void testTypeInfoSimpleTypes() {
    runTest("pika-compiler/testData/box/typeInfoSimpleTypes.kt");
  }

  @Test
  @TestMetadata("typeInfoStarProjection.kt")
  public void testTypeInfoStarProjection() {
    runTest("pika-compiler/testData/box/typeInfoStarProjection.kt");
  }
}
