

package io.github.lukmccall.pika.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.lukmccall.pika.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("pika-compiler/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("pika-compiler/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("introspectableAnnotations.kt")
  public void testIntrospectableAnnotations() {
    runTest("pika-compiler/testData/box/introspectableAnnotations.kt");
  }

  @Test
  @TestMetadata("introspectableBackingField.kt")
  public void testIntrospectableBackingField() {
    runTest("pika-compiler/testData/box/introspectableBackingField.kt");
  }

  @Test
  @TestMetadata("introspectableBasic.kt")
  public void testIntrospectableBasic() {
    runTest("pika-compiler/testData/box/introspectableBasic.kt");
  }

  @Test
  @TestMetadata("introspectableDataClass.kt")
  public void testIntrospectableDataClass() {
    runTest("pika-compiler/testData/box/introspectableDataClass.kt");
  }

  @Test
  @TestMetadata("introspectableEmpty.kt")
  public void testIntrospectableEmpty() {
    runTest("pika-compiler/testData/box/introspectableEmpty.kt");
  }

  @Test
  @TestMetadata("introspectableFunctions.kt")
  public void testIntrospectableFunctions() {
    runTest("pika-compiler/testData/box/introspectableFunctions.kt");
  }

  @Test
  @TestMetadata("introspectableIndirectInheritance.kt")
  public void testIntrospectableIndirectInheritance() {
    runTest("pika-compiler/testData/box/introspectableIndirectInheritance.kt");
  }

  @Test
  @TestMetadata("introspectableInheritance.kt")
  public void testIntrospectableInheritance() {
    runTest("pika-compiler/testData/box/introspectableInheritance.kt");
  }

  @Test
  @TestMetadata("introspectableObject.kt")
  public void testIntrospectableObject() {
    runTest("pika-compiler/testData/box/introspectableObject.kt");
  }

  @Test
  @TestMetadata("introspectableSetterComputed.kt")
  public void testIntrospectableSetterComputed() {
    runTest("pika-compiler/testData/box/introspectableSetterComputed.kt");
  }

  @Test
  @TestMetadata("introspectableSetterVal.kt")
  public void testIntrospectableSetterVal() {
    runTest("pika-compiler/testData/box/introspectableSetterVal.kt");
  }

  @Test
  @TestMetadata("introspectableValVsVar.kt")
  public void testIntrospectableValVsVar() {
    runTest("pika-compiler/testData/box/introspectableValVsVar.kt");
  }

  @Test
  @TestMetadata("introspectableVisibility.kt")
  public void testIntrospectableVisibility() {
    runTest("pika-compiler/testData/box/introspectableVisibility.kt");
  }

  @Test
  @TestMetadata("pIntrospectionOf.kt")
  public void testPIntrospectionOf() {
    runTest("pika-compiler/testData/box/pIntrospectionOf.kt");
  }

  @Test
  @TestMetadata("typeInfoCustomClass.kt")
  public void testTypeInfoCustomClass() {
    runTest("pika-compiler/testData/box/typeInfoCustomClass.kt");
  }

  @Test
  @TestMetadata("typeInfoNestedGenerics.kt")
  public void testTypeInfoNestedGenerics() {
    runTest("pika-compiler/testData/box/typeInfoNestedGenerics.kt");
  }

  @Test
  @TestMetadata("typeInfoParameterized.kt")
  public void testTypeInfoParameterized() {
    runTest("pika-compiler/testData/box/typeInfoParameterized.kt");
  }

  @Test
  @TestMetadata("typeInfoProxyInline.kt")
  public void testTypeInfoProxyInline() {
    runTest("pika-compiler/testData/box/typeInfoProxyInline.kt");
  }

  @Test
  @TestMetadata("typeInfoSimpleTypes.kt")
  public void testTypeInfoSimpleTypes() {
    runTest("pika-compiler/testData/box/typeInfoSimpleTypes.kt");
  }

  @Test
  @TestMetadata("typeInfoStarProjection.kt")
  public void testTypeInfoStarProjection() {
    runTest("pika-compiler/testData/box/typeInfoStarProjection.kt");
  }
}
