@file:OptIn(UnsafeDuringIrConstructionAPI::class)

package io.github.lukmccall.pika.ir

import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.descriptors.Modality
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrGetValueImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrReturnImpl
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.classOrNull
import org.jetbrains.kotlin.ir.types.typeWith
import org.jetbrains.kotlin.ir.util.defaultType
import org.jetbrains.kotlin.ir.util.isInterface
import org.jetbrains.kotlin.ir.util.kotlinFqName
import org.jetbrains.kotlin.ir.visitors.IrTransformer
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * IR transformer that generates `__PIntrospectionData()` functions for classes
 * that implement the Introspectable marker interface.
 */
class IntrospectableTransformer(
  private val context: IrPluginContext,
  private val poet: IRPoet,
  private val symbolFinder: SymbolFinder
) : IrTransformer<Nothing?>() {

  companion object {
    private val INTROSPECTABLE_FQN = FqName("io.github.lukmccall.pika.Introspectable")
    private const val INTROSPECTION_DATA_FUNCTION_NAME = "__PIntrospectionData"
  }

  override fun visitClass(declaration: IrClass, data: Nothing?): IrStatement {
    declaration.transformChildren(this, data)

    if (shouldGenerate(declaration)) {
      generateIntrospectionDataFunction(declaration)
    }

    return declaration
  }

  /**
   * Check if we should generate introspection data for this class.
   */
  private fun shouldGenerate(irClass: IrClass): Boolean {
    // Skip interfaces and abstract classes
    if (irClass.isInterface || irClass.modality == Modality.ABSTRACT) {
      return false
    }

    // Check if __PIntrospectionData function exists (generated by FIR extension)
    val existingFunction = irClass.declarations
      .filterIsInstance<IrSimpleFunction>()
      .find { it.name.asString() == INTROSPECTION_DATA_FUNCTION_NAME }

    // If function already has a body, skip (already processed)
    if (existingFunction?.body != null) {
      return false
    }

    // Check if class implements Introspectable (directly or indirectly)
    return implementsIntrospectable(irClass)
  }

  /**
   * Check if the class implements Introspectable interface (directly or via inheritance).
   */
  private fun implementsIntrospectable(irClass: IrClass): Boolean {
    return irClass.superTypes.any { superType ->
      val superClass = (superType as? IrSimpleType)?.classOrNull?.owner ?: return@any false

      if (superClass.kotlinFqName == INTROSPECTABLE_FQN) {
        return@any true
      }

      // Recursively check superclass
      implementsIntrospectable(superClass)
    }
  }

  /**
   * Generate the __PIntrospectionData() function body for the class.
   * The function declaration is created by the FIR extension.
   */
  private fun generateIntrospectionDataFunction(irClass: IrClass) {
    // Find the existing FIR-generated function
    val function = irClass.declarations
      .filterIsInstance<IrSimpleFunction>()
      .find { it.name.asString() == INTROSPECTION_DATA_FUNCTION_NAME }
      ?: return // Should not happen if FIR extension is working

    // Build properties list (only properties declared directly on this class)
    val properties = irClass.declarations
      .filterIsInstance<IrProperty>()
      .filter { !it.isFakeOverride }
      .map { property ->
        poet.pika.pProperty(property, irClass, function, context.irFactory)
      }

    // Build functions list (only functions declared directly on this class, excluding special ones)
    val functions = irClass.declarations
      .filterIsInstance<IrSimpleFunction>()
      .filter { func ->
        // Exclude constructors, property accessors, the generated function, and fake overrides
        !func.name.isSpecial &&
          !func.isFakeOverride &&
          func.correspondingPropertySymbol == null &&
          func.name.asString() != INTROSPECTION_DATA_FUNCTION_NAME &&
          func.name.asString() != "<init>"
      }
      .map { func ->
        poet.pika.pFunction(func)
      }

    // Build base class reference if parent implements Introspectable
    val baseClassExpr = buildBaseClassReference(irClass, function)

    val introspectionData = poet.pika.pIntrospectionData(
      irClass = irClass,
      properties = properties,
      functions = functions,
      baseClassExpr = baseClassExpr,
      irFactory = context.irFactory
    )

    function.body = context.irFactory.createBlockBody(-1, -1).apply {
      statements.add(
        IrReturnImpl(
          startOffset = -1,
          endOffset = -1,
          type = context.irBuiltIns.nothingType,
          returnTargetSymbol = function.symbol,
          value = introspectionData
        )
      )
    }
  }

  /**
   * Build a call to the parent's __PIntrospectionData() function if the parent
   * implements Introspectable, otherwise return null.
   */
  private fun buildBaseClassReference(irClass: IrClass, containingFunction: IrSimpleFunction): IrExpression? {
    val superClass = irClass.superTypes
      .filterIsInstance<IrSimpleType>()
      .filter { !it.isInterface() }
      .mapNotNull { it.classOrNull?.owner }
      .firstOrNull { it.kotlinFqName.asString() != "kotlin.Any" }
      ?: return null

    // Check if parent implements Introspectable
    if (!implementsIntrospectable(superClass)) {
      return null
    }

    // Find the __PIntrospectionData function on the parent
    val parentFunction = superClass.declarations
      .filterIsInstance<IrSimpleFunction>()
      .find { it.name.asString() == INTROSPECTION_DATA_FUNCTION_NAME }

    // If the parent is also being transformed, it may not have the function yet.
    // In that case, we'll build a call assuming it will exist.
    val pIntrospectionDataClass = symbolFinder.pikaAPI.pIntrospectionData
    val parentReturnType = pIntrospectionDataClass.typeWith(superClass.defaultType)

    if (parentFunction != null) {
      return IrCallImpl(
        startOffset = -1,
        endOffset = -1,
        type = parentReturnType,
        symbol = parentFunction.symbol,
        typeArgumentsCount = 0,
        origin = null,
        // Use superQualifierSymbol to make this a super call, avoiding infinite recursion
        superQualifierSymbol = superClass.symbol
      ).apply {
        // The parent's __PIntrospectionData is called on 'this' (the dispatch receiver of the containing function)
        dispatchReceiver = containingFunction.dispatchReceiverParameter?.let {
          IrGetValueImpl(
            startOffset = -1,
            endOffset = -1,
            type = irClass.defaultType,
            symbol = it.symbol
          )
        }
      }
    }

    return null
  }
}
