package io.github.lukmccall.pika

/**
 * Marker interface for classes that should have introspection data generated.
 * Classes implementing this interface (directly or indirectly) will have a
 * `__PIntrospectionData()` function generated by the compiler plugin.
 */
public interface Introspectable
