package io.github.lukmccall.pika

/**
 * Marker annotation for classes that should have introspection data generated.
 * Classes annotated with this (directly or indirectly via inheritance) will have a
 * `__PIntrospectionData()` function generated by the compiler plugin.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
public annotation class Introspectable
