package io.github.lukmccall.pika

/**
 * Marker annotation for classes that should have introspection data generated.
 * Classes annotated with this will have a cached introspection data field
 * generated by the compiler plugin.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
public annotation class Introspectable
